services:
  devcontainer:
    image: ros2_so101:base
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: jazzy
      target: base

    # === Tune this to your application ===
    # network_mode: "host"
    ipc: "host"
    pid: "host"
    privileged: true
    # ===

    ports:
      - 3389:3389

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: /bin/bash
    tty: true
    stdin_open: true

    volumes:
   #   - $HOME/.Xauthority:/root/.Xauthority # X11 Passtrough
   #   - /tmp/.X11-unix:/tmp/.X11-unix:rw # X11 Passtrough
      - ../limits.conf:/etc/security/limits.conf

    environment:
  #    QT_X11_NO_MITSHM: 1 # X11 Passtrough
  #    DISPLAY: $DISPLAY # X11 Passtrough
      DISPLAY: :10.0 # RDP
      ROS_DOMAIN_ID: 100
      RCUTILS_COLORIZED_OUTPUT: 1
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      SHELL: /bin/bash

    cap_add:
      - SYS_NICE

    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
